### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by potenzatk** [Azure-Samples/active-directory-b2c-php-webapp-openidconnect#11]
Hello,

Please help for resolve the issue

file_get_contents(https://login.microsoftonline.com/perituzaADB2C.onmicrosoft.com.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_pgsb2capp): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

https://prnt.sc/tacavu

**Comment by rodion-arr** [comment]
Hi,

Your URL looks like not correct.
Here is `common` example - https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

The `common` URL part can be replaced with you tenant ID like this - https://login.microsoftonline.com/97b93aeb-9282-46f9-bcfc-8de826694a0e/v2.0/.well-known/openid-configuration

More info here - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

**Comment by potenzatk** [comment]
Thanks For your replay.

We just want to authenticate user with azure AD b2c in php is there any simple example. Please send us link

**Comment by potenzatk** [comment]
The URL code is located on your settings.php file

File Path: active-directory-b2c-php-webapp-openidconnect/app/Http/Controllers/settings.php

So we need to update the code.

We have tried this but still not working.

https://prnt.sc/tae9bs

Thanks

**Comment by rodion-arr** [comment]
1. You have `onmicrosoft.com` twice in you URL
1. You policy may be not configured correctly

This URL works - https://login.microsoftonline.com/perituzaADB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration

**Comment by potenzatk** [comment]
Thanks for your reply.

We have fixed this issue. now we got below error.
https://prnt.sc/tb7zrz

Undefined index: emails Please check and let us know how we can fix this.

**Comment by potenzatk** [comment]
We are gatting AADB2C90289: We encountered an error connecting to the identity provider. Please try again later
error for default directory login

**Comment by jmprieur** [comment]
Archiving this sample
