### ISSUE TITLE
Access token validation failure (/me)

### ISSUE THREAD

**Issue by alessander-maia** [Azure-Samples/active-directory-b2c-php-webapp-openidconnect#12]
Hello,

Can you please help me solve this problem?

I am getting the access token, but when I call "/ me" it returns this error:

PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ClientException: Client error: `GET https://graph.microsoft.com/v1.0/me` resulted in a `401 Unauthorized` response:\n{\r\n  "error": {\r\n    "code": "InvalidAuthenticationToken",\r\n    "message": "Access token validation failure."

My endpoints: 
https://aniversariooutbackdev.b2clogin.com/aniversariooutbackdev.onmicrosoft.com/B2C_1A_signup_signin/oauth2/v2.0/authorize

https://aniversariooutbackdev.b2clogin.com/aniversariooutbackdev.onmicrosoft.com/B2C_1A_signup_signin/oauth2/v2.0/token

**Comment by jmprieur** [comment]
Archiving this sample
