### ISSUE TITLE
Trouble with the sample

### ISSUE THREAD

**Issue by maximeplanteemyode** [Azure-Samples/active-directory-b2c-php-webapp-openidconnect#2]
Hi there,

When trying to make the sample website work, we get a database error.(at the moment of writing this message)

Nor is it very precise on which version of PHP (and architecture) you should use, as well as which version of Laravel to use.

Now, after we followed the few scarce steps provided (and have to comments a few things to enable composer to do it's job, the authentication never works and gives an HTTP 500 error when trying to login (not even showing the B2C login prompt).

Are we missing something here? @t-olhuan, @olenah 

Any feedback/help would be appreciated.

**Comment by nhitze** [comment]
I too have this issue, so the sample right now is totally useless. 

Also @parakhj why have you closed the issue without any reply?
