### ISSUE TITLE
Why Lavarel

### ISSUE THREAD

**Issue by aw-creative** [Azure-Samples/active-directory-b2c-php-webapp-openidconnect#8]
Can you just use a simple example and class to do your example apps, The whole concept of a sample is a standalone example, How are people meant to learn when the whole thing is wrapped in an overly complex package

**Comment by aw-creative** [comment]
This Example is no longer usable in a new lavarel project.

**Comment by mhenkel1** [comment]
> This Example is no longer usable in a new lavarel project.

The code of this example isn't even following Laravel best practices...
Hard to read and did not use any of the advantages laravel provides. :/
