### ISSUE TITLE
redirection issue

### ISSUE THREAD

**Issue by pankajmonga10** [Azure-Samples/active-directory-b2c-php-webapp-openidconnect#9]
If I configure only sign-in policy with the plugin then after login with active directory, user is is being redirected to site home page. Post login, even if i try to navigate to wp-admin again it is being redirected to the site home page only. I am unable to access the wordpress admin dashboard post successful login. This behaviour is working fine if i configure both sign up and sign in policies.

**Comment by jmprieur** [comment]
Archiving this sample
